Repository Nidhoogr/Yggdrasil, pull requests merged in 2021-03, with the labels that each got.

#49 feat: write premisse
  package-lock.json
  package.json
  premissa.md
Labels: documentation

#53 feat: added endscene and animations
  client/src/assets/audio/jump/index.js
  client/src/assets/audio/jump/jump_01.mp3
  client/src/assets/audio/jump/jump_02.mp3
  client/src/assets/audio/jump/jump_03.mp3
  client/src/assets/audio/jump/jump_04.mp3
  client/src/assets/audio/jump/jump_05.mp3
  client/src/assets/audio/jump/jump_06.mp3
  client/src/assets/audio/jump/jump_07.mp3
  client/src/assets/audio/jump/jump_08.mp3
  client/src/assets/audio/jump/jump_09.mp3
  client/src/assets/audio/jump/jump_10.mp3
  client/src/assets/audio/jump/jump_11.mp3
  client/src/assets/img/32x32 Pink Block.png
  client/src/assets/img/background/sky_fc.png
  client/src/assets/img/ground.png
  client/src/assets/img/player/jump.png
  client/src/assets/img/player/run.png
  client/src/assets/index.js
  client/src/index.js
  client/src/scenes/EndGameScene.js
  client/src/scenes/GameScene.js
  client/src/scenes/GameScene.old.js
  client/src/scenes/ModeSelectionScene.js
  client/src/scenes/TitleScene.js
  server/server.js
Labels: Coding, documentation

#54 Dev
  client/src/assets/audio/jump/index.js
  client/src/assets/audio/jump/jump_01.mp3
  client/src/assets/audio/jump/jump_02.mp3
  client/src/assets/audio/jump/jump_03.mp3
  client/src/assets/audio/jump/jump_04.mp3
  client/src/assets/audio/jump/jump_05.mp3
  client/src/assets/audio/jump/jump_06.mp3
  client/src/assets/audio/jump/jump_07.mp3
  client/src/assets/audio/jump/jump_08.mp3
  client/src/assets/audio/jump/jump_09.mp3
  client/src/assets/audio/jump/jump_10.mp3
  client/src/assets/audio/jump/jump_11.mp3
  client/src/assets/img/32x32 Pink Block.png
  client/src/assets/img/background/layer0.png
  client/src/assets/img/background/layer1.png
  client/src/assets/img/background/layer2.2.png
  client/src/assets/img/background/layer2.png
  client/src/assets/img/background/layer3.png
  client/src/assets/img/background/layer4.png
  client/src/assets/img/ground.png
  client/src/assets/img/player/jump.png
  client/src/assets/img/player/run.png
  client/src/assets/index.js
  client/src/index.js
  client/src/scenes/EndGameScene.js
  client/src/scenes/GameScene.js
  client/src/scenes/GameScene.old.js
  client/src/scenes/ModeSelectionScene.js
  client/src/scenes/TitleScene.js
  server/server.js
Labels: Coding
